import Head from "next/head";
import { ReactNode } from "react";
import Footer from "../../components/Footer";
import Menu from "../../components/Menu";

interface LayoutProps {
  title?: string;
  children?: ReactNode;
}

export const SimpleLayout = ({ children, title }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      {children}
      <Footer />
    </>
  );
};
