import Head from "next/head";
import Footer from "../../components/Footer";
import Menu from "../../components/Menu";

export const DefaultLayout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      {children}
      <Footer />
    </>
  );
};
